name:
  CI
on:
  [push, pull_request]
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ["debian-buster", "debian-bullseye", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Testing README.md instructions
        env:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}
        run: |
          .github/docker/launcher.sh
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executed-test-scripts
          path: |
            ~/${{ github.event.repository.name }}_${{ matrix.docker_image }}/${{ github.event.repository.name }}_${{ matrix.docker_image }}.sh
  release:
    name: Create Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Changelog Pruning
        run: |
          sed -n `awk '/## \[${{ github.ref_name }}/{c++} c==1{ print NR; exit }' CHANGELOG.md`',$p' CHANGELOG.md > .CHANGELOG.md.tmp
          sed `awk '/## \[[x0-9]/{c++} c==2{ print NR; exit }' .CHANGELOG.md.tmp`',$d' .CHANGELOG.md.tmp > ${{ github.workspace }}-CHANGELOG.txt
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          files: |
            LICENSE
